import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="flex flex-row border-b-2 p-2">
          <Image className="p-2" src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          <h1 className="text-left p-2">Joselyn Website</h1>
        </div>

        {children}
      </body>
    </html>
  )
}
